In [2]:
#1. Import the NUMPY package under the name np.
import numpy as np

In [3]:
#2. Print the NUMPY version and the configuration.

np.version.version



'1.16.2'

In [4]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

a = np.random.random((2,3,5))
b = np.random.random_sample((2,3,5))
c = np.random.sample((2,3,5))
d = np.random.ranf((2,3,5))

#4. Print a.
print(a,b,c,d)




[[[0.2020256  0.48858402 0.32721386 0.86840091 0.66527617]
  [0.05315806 0.4936948  0.64776313 0.71582496 0.73968666]
  [0.09391764 0.5976446  0.77466297 0.66339724 0.04300999]]

 [[0.27104477 0.21352873 0.20371046 0.6985439  0.31226022]
  [0.90367591 0.64582871 0.25061713 0.01428002 0.24210229]
  [0.87709864 0.86364866 0.94717681 0.34102991 0.45492566]]] [[[0.08976979 0.01978695 0.49016534 0.99737409 0.55039386]
  [0.71745677 0.01056832 0.03317513 0.87025671 0.87612397]
  [0.32632167 0.87560207 0.86030527 0.5423923  0.0244725 ]]

 [[0.95710785 0.11996266 0.64616026 0.25076022 0.36388632]
  [0.54756593 0.91903605 0.58595959 0.89662438 0.12370205]
  [0.0126601  0.76062153 0.60858001 0.9137966  0.5585143 ]]] [[[0.90319177 0.16151456 0.73227816 0.93525813 0.25464879]
  [0.73740173 0.33516036 0.53164991 0.26582933 0.68641685]
  [0.82286097 0.76311989 0.23152725 0.52754757 0.22236086]]

 [[0.70224156 0.43600726 0.39566097 0.8154623  0.49609851]
  [0.05453363 0.91222973 0.92367388 0.71021656

In [5]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

b = np.ones((5,2,3), dtype=int)

#6. Print b.

print(b)


[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


In [6]:
#7. Do a and b have the same size? How do you prove that in Python code?

print(a.shape == c.shape)

print(a.shape)
print(b.shape)

#8. Are you able to add a and b? Why or why not?





True
(2, 3, 5)
(5, 2, 3)


In [53]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

b = np.ones((2, 3, 5))

#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

d = np.sum((a, c), axis = 0)

#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.
print(a)
print('-' * 60)
print(d)
  


[[[0.2020256  0.48858402 0.32721386 0.86840091 0.66527617]
  [0.05315806 0.4936948  0.64776313 0.71582496 0.73968666]
  [0.09391764 0.5976446  0.77466297 0.66339724 0.04300999]]

 [[0.27104477 0.21352873 0.20371046 0.6985439  0.31226022]
  [0.90367591 0.64582871 0.25061713 0.01428002 0.24210229]
  [0.87709864 0.86364866 0.94717681 0.34102991 0.45492566]]]
------------------------------------------------------------
[[[1.10521737 0.65009858 1.05949203 1.80365903 0.91992496]
  [0.79055979 0.82885516 1.17941303 0.98165429 1.42610351]
  [0.91677862 1.36076449 1.00619023 1.19094481 0.26537085]]

 [[0.97328633 0.649536   0.59937143 1.5140062  0.80835873]
  [0.95820954 1.55805844 1.174291   0.72449659 0.7020934 ]
  [1.48240607 1.68064331 1.18700761 1.12450142 1.42882443]]]


In [50]:
#12. Multiply a and c. Assign the result to e.

e = np.multiply(a, c)

#11. Print a and e. Notice the difference and relation of the two array in terms of the values? Explain.
print(a)
print('-' * 60)
print(e)
  


#13. Does e equal to a? Why or why not?




[[[0.2020256  0.48858402 0.32721386 0.86840091 0.66527617]
  [0.05315806 0.4936948  0.64776313 0.71582496 0.73968666]
  [0.09391764 0.5976446  0.77466297 0.66339724 0.04300999]]

 [[0.27104477 0.21352873 0.20371046 0.6985439  0.31226022]
  [0.90367591 0.64582871 0.25061713 0.01428002 0.24210229]
  [0.87709864 0.86364866 0.94717681 0.34102991 0.45492566]]]
------------------------------------------------------------
[[[0.18246786 0.07891343 0.23961157 0.81217901 0.16941177]
  [0.03919884 0.16546693 0.34438321 0.19028727 0.50773339]
  [0.07728116 0.45607448 0.17935559 0.3499736  0.00956374]]

 [[0.1903389  0.09310008 0.08060028 0.56963621 0.15491183]
  [0.04928073 0.58914415 0.23148849 0.01014191 0.1113649 ]
  [0.53091432 0.70559633 0.22716216 0.26718722 0.44305154]]]


In [54]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

d_max = np.amax(d)
d_min = np.amin(d)
d_mean = np.mean(d)
# print(d_max, d_min, d_mean)

#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

f = np.empty((2,3,5))

print(f)
print(d_min)


[[[1.10521737 0.65009858 1.05949203 1.80365903 0.91992496]
  [0.79055979 0.82885516 1.17941303 0.98165429 1.42610351]
  [0.91677862 1.36076449 1.00619023 1.19094481 0.26537085]]

 [[0.97328633 0.649536   0.59937143 1.5140062  0.80835873]
  [0.95820954 1.55805844 1.174291   0.72449659 0.7020934 ]
  [1.48240607 1.68064331 1.18700761 1.12450142 1.42882443]]]
0.26537085397518534


In [40]:
lst = [2,3,5,6,7,8,12,15,23]

In [56]:
"""
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""

for index1, _1stlayer in enumerate(d):
    for index2, _2ndlayer in enumerate(_1stlayer):
        for index3, _3rdlayer in enumerate(_2ndlayer):
            if (_3rdlayer == d_mean):
                print(_3rdlayer)
                f[index1][index2][index3] = float(50)
            if (_3rdlayer == d_max):
                f[index1][index2][index3] = float(100)
            if (_3rdlayer == d_min):
                f[index1][index2][index3] = float(0)
            if (_3rdlayer >= d_min) & (_3rdlayer < d_mean):
                f[index1][index2][index3] = float(25)
            if (_3rdlayer > d_mean) & (_3rdlayer < d_max):
                f[index1][index2][index3] = float(75)
print(d)
print(f)


[[[1.10521737 0.65009858 1.05949203 1.80365903 0.91992496]
  [0.79055979 0.82885516 1.17941303 0.98165429 1.42610351]
  [0.91677862 1.36076449 1.00619023 1.19094481 0.26537085]]

 [[0.97328633 0.649536   0.59937143 1.5140062  0.80835873]
  [0.95820954 1.55805844 1.174291   0.72449659 0.7020934 ]
  [1.48240607 1.68064331 1.18700761 1.12450142 1.42882443]]]
[[[ 75.  25.  25. 100.  25.]
  [ 25.  25.  75.  25.  75.]
  [ 25.  75.  25.  75.  25.]]

 [[ 25.  25.  25.  75.  25.]
  [ 25.  75.  75.  25.  25.]
  [ 75.  75.  75.  75.  75.]]]


In [49]:
f

array([[[  1.10521737,  25.        ,  25.        , 100.        ,
          25.        ],
        [ 25.        ,  25.        ,   1.17941303,  25.        ,
           1.42610351],
        [ 25.        ,   1.36076449,  25.        ,   1.19094481,
           0.26537085]],

       [[ 25.        ,  25.        ,  25.        ,   1.5140062 ,
          25.        ],
        [ 25.        ,   1.55805844,   1.174291  ,  25.        ,
          25.        ],
        [  1.48240607,   1.68064331,   1.18700761,   1.12450142,
           1.42882443]]])

In [10]:
"""
#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""

'\n#17. Print d and f. Do you have your expected f?\nFor instance, if your d is:\narray([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],\n        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],\n        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],\n\n       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],\n        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],\n        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])\n\nYour f should be:\narray([[[ 75.,  75.,  75.,  25.,  75.],\n        [ 75.,  75.,  25.,  25.,  25.],\n        [ 75.,  25.,  75.,  75.,  75.]],\n\n       [[ 25.,  25.,  25.,  25., 100.],\n        [ 75.,  75.,  75.,  75.,  75.],\n        [ 25.,  75.,   0.,  75.,  75.]]])\n'

In [11]:
"""
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
"""

'\n#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values \n("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:\narray([[[ \'D\',  \'D\',  \'D\',  \'B\',  \'D\'],\n        [ \'D\',  \'D\',  \'B\',  \'B\',  \'B\'],\n        [ \'D\',  \'B\',  \'D\',  \'D\',  \'D\']],\n\n       [[ \'B\',  \'B\',  \'B\',  \'B\',  \'E\'],\n        [ \'D\',  \'D\',  \'D\',  \'D\',  \'D\'],\n        [ \'B\',  \'D\',   \'A\',  \'D\', \'D\']]])\nAgain, you don\'t need Numpy in this question.\n'